### ISSUE TITLE
[bug] Pod exec/attach fails silently in case of errors

### ISSUE THREAD

**Issue by Martin-4Spaces** [renoki-co/php-k8s#185]
When calling pod exec https://php-k8s.renoki.org/resources/workloads/pod#pod-exec with `KubernetesCluster::fromKubeConfigYamlFile` it works fine. 
But when authenticating with `KubernetesCluster::inClusterConfiguration()` it does not work. No errors. Just no connection established and therefore no messages returned. 
All other api endpoints works fine with in-cluster authentication.

The pod service account has the following Cluster Role rules:
```
rules:
  - apiGroups: ["", "batch", "cert-manager.io", "extensions", "apps", "networking.k8s.io"]
    resources:
      - pods
      - jobs
      - pods/log
      - pods/exec
      - pods/attach
      - certificates
      - cronjobs
      - persistentvolumes
      - persistentvolumeclaims
      - deployments
      - services
      - ingresses
      - namespaces
    verbs:
      - get
      - list
      - create
      - delete
      - patch
```

As far as I understand the `pods/exec` and `get` verb should be sufficient. 
I hope anyone can help me figure this one out.. Thank you. Can anyone else establish a web socket connection when using in-cluster authentication?
