### ISSUE TITLE
delete() does not remove resources imported from YAML

### ISSUE THREAD

**Issue by buzanits** [renoki-co/php-k8s#258]
I can create and update resources with
```
$x = $cluster->fromYaml($code);
$x->createOrUpdate();
```
But when doing
```
$x = $cluster->fromYaml($code);
$x->delete();
```
with the same `$code` the resources do not get deleted. Deleting works when I do
`kubectl delete -f code.yaml`
having the content of `$code` in the `code.yaml`.

**Comment by buzanits** [comment]
btw this is the `$code` used for this test:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test1
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy:
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/test1
    server: 10.255.3.203
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test1-pvc
spec:
  storageClassName: ""
  volumeName: nfs-test1
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1G
```

**Comment by buzanits** [comment]
btw this is the `$code` used in this test:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test1
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy:
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/test1
    server: 10.255.3.203
    readOnly: false

```
