### ISSUE TITLE
Enabeling TLS on k8s ingress

### ISSUE THREAD

**Issue by svenvanhees** [renoki-co/php-k8s#69]
Is there any way we can add tls hosts and a secretName to the ingress definition? Looked trough the code but could not find any way to set the tls hosts attribute, while also specifying the secretName.

````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-example-ingress
spec:
  tls:
  - hosts:
      - https-example.foo.com
    secretName: testsecret-tls
  rules:
  - host: https-example.foo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
````

Maybe there could be something like this?

```
$ing = $this->cluster->ingress()
            ->setName('nginx')
            ->setLabels(['tier' => 'backend'])
            ->setAnnotations(['nginx/ann' => 'yes'])
            ->setTls([
                    'hosts' => [
                        'api.example.com',
                        'test.example.com',
                    ],
                    'secretName' => 'test'
                ])
```
