### ISSUE TITLE
Feature Request: Allow secret refs as env's

### ISSUE THREAD

**Issue by svenvanhees** [renoki-co/php-k8s#84]
It would be great if we could use secrets to populate env's.

```
- name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
```

Was thinking we could add 2 new functions to the Container kind. While also editing the ->setEnv() function to allow for a valueFrom key to be set.

I tried the following, but it does not work yet...
```
  /**
     * Add an env variable by using a secret reference to the container.
     *
     * @param  string  $name
     * @param  string  $refName
     * @param  string  $refKey
     * @return $this
     */
    public function addSecretKeyRef(string $name, string $refName, string $refKey)
    {
        return $this->addToAttribute('env', [
            'name' => $name,
            'valueFrom' => [
                'secretKeyRef' => [
                    'name' => $refName,
                    'key' => $refKey
                ]
            ]
        ]);
    }
```
Any Ideas/suggestions?

p.s. Great work on the package overall !

Kubernetes References:
[https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)
[https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#envvarsource-v1-core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#envvarsource-v1-core)

**Comment by rennokki** [comment]
This seems well done overall. Perhaps this would be needed for [ConfigMaps as well](https://kubernetes.io/docs/concepts/configuration/configmap/):

```yaml
env:
  - name: game
    valueFrom:
      configMapKeyRef:
        name: game-demo      # The ConfigMap this value comes from.
        key: player_initial_lives # The key to fetch.
```

Also, [Field Refs](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables), which I've used recently and they do a great job to get the current pod details directly into the pod:

```yaml
env:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
```

The secrets seem the most obvious and used one, we can catch up with CM and fieldrefs afterward.
